AWSTemplateFormatVersion: "2010-09-09"
Description: "This CFT is to create EC2 instance in AWS"
Parameters:
  SSHKey:
    Type: AWS::EC2::KeyPair::KeyName
    Description: "SSH into EC2 instance"
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: "VPC ID"
  EC2ImageID:
    Type: AWS::EC2::Image::Id
    Description: "EC2 Image ID"
Resources:
  DummyServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref EC2ImageID
      InstanceType: t2.micro
      KeyName: !Ref SSHKey
      SecurityGroupIds:
        - !GetAtt
          - SSHSecurityGroup
          - GroupId

  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22